# Generated by Django 5.1.1 on 2024-09-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='severity',
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('severity', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('tag', models.ManyToManyField(to='symptoms.diagnosis')),
            ],
        ),
    ]
