# Generated by Django 5.1.1 on 2024-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersymptomlog',
            name='type_of_pain',
        ),
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.CharField(default='OTC', max_length=255),
        ),
        migrations.AddField(
            model_name='usermedicationlog',
            name='associated_symptoms',
            field=models.ManyToManyField(to='symptoms.symptom'),
        ),
        migrations.AddField(
            model_name='usersymptomlog',
            name='is_numerical',
            field=models.BooleanField(default=True),
        ),
    ]
