# Generated by Django 5.1.1 on 2024-09-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_diagnosis_remove_symptom_severity_patientdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='PatientSymptom',
            old_name='tag',
            new_name='diagnosis',
        ),
    ]
