# Generated by Django 5.1.1 on 2024-11-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_remove_usersymptomlog_type_of_pain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='Units',
            field=models.CharField(default='lbs', max_length=50),
        ),
        migrations.AddField(
            model_name='symptom',
            name='category',
            field=models.CharField(default='Numerical', max_length=100),
        ),
    ]
