# Generated by Django 5.1.1 on 2024-09-27 19:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_rename_tag_patientdata_illness'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='patientsymptom',
            old_name='time',
            new_name='onset_modified',
        ),
        migrations.RemoveField(
            model_name='patientsymptom',
            name='notes',
        ),
        migrations.AddField(
            model_name='patientsymptom',
            name='onset_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 19, 10, 5, 272477)),
        ),
        migrations.AddField(
            model_name='patientsymptom',
            name='set_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientsymptom',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dosage', models.FloatField()),
                ('notes', models.CharField(max_length=1000)),
                ('set_reminder', models.BooleanField(default=False)),
                ('diagnosis', models.ManyToManyField(to='symptoms.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('frequency', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='symptoms.patientmedication')),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='symptoms.patientsymptom')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='symptoms.user'),
        ),
    ]
