# Generated by Django 5.1.1 on 2024-11-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_rename_s_id_usersymptomlog_symptom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersymptomlog',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, related_name='symptom_logs', to='symptoms.diagnosis'),
        ),
    ]
