# Generated by Django 5.1.1 on 2024-10-01 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0005_alter_patientsymptom_onset_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='patientsymptom',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='symptom',
        ),
        migrations.AddField(
            model_name='reminder',
            name='s_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='symptoms.symptom'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='symptom',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='m_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='symptoms.medication'),
        ),
        migrations.CreateModel(
            name='UserMedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=255, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('log_time', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.medication')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(null=True)),
                ('onset_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_of_pain', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('value', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('diagnosis', models.ManyToManyField(to='symptoms.diagnosis')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.symptom')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientMedication',
        ),
        migrations.DeleteModel(
            name='PatientSymptom',
        ),
    ]
